name: PR Build

on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - main

env:
  MAVEN_ARGS: "--batch-mode --no-transfer-progress"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up mise
        uses: jdx/mise-action@v2

      - name: Activate mise
        run: |
          mise env --dotenv >> $GITHUB_ENV

      - name: Test
        run: |
          ./mvnw ${{ env.MAVEN_ARGS }} clean verify

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6
        if: success() || failure()

        with:
          check_name: |
            JUnit Test Report
          report_paths: |
            **/target/surefire-reports/TEST-*.xml
          include_passed: true
          include_time_in_summary: true
